CFLAGS=-lpthread -Wall -g
thread1:thread1.c
	$(CC) -o $@ $^  $(CFLAGS)
thread2:thread2.c
	$(CC) -o $@ $^ $(CFLAGS)
thread3:thread3.c
	$(CC) -o $@ $^ $(CFLAGS)
thread4:thread4.c
	$(CC) -o $@ $^ $(CFLAGS)
thread5:thread5.c
	$(CC) -o $@ $^ $(CFLAGS)
thread6:thread6.c
	$(CC) -o $@ $^ $(CFLAGS)
thread7:thread7.c
	$(CC) -o $@ $^ $(CFLAGS)
printtid:printtid.c
	$(CC) -o $@ $^ $(CFLAGS)
thread_exit:thread_exit.c
	$(CC) -o $@ $^ $(CFLAGS)
sum:sum.c
	$(CC) -o $@ $^ $(CFLAGS)
