readmark:readmark.c
	gcc -Wall -g readmark.c -o readmark
t:t.c
	gcc -Wall -g t.c -o t
t1:t1.c
	gcc -Wall -g t1.c -o t1
char:char.c
	gcc -Wall -g char.c -o char
deletemark:deletemark.c
	gcc -Wall -g deletemark.c -o deletemark
fseek:fseek.c
	gcc -Wall -g fseek.c -o fseek
