#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Ubuntu 13.04 ISO" {
	insmod ntfs
	set isofile="/packages/iso/ubuntu-13.04-desktop-amd64.iso"
	#isofile is the path of iso file in the corresponding partition 
	loopback loop (hd0,6)$isofile
	linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=$isofile noprompt noeject
	initrd (loop)/casper/initrd.lz
}

menuentry "Android 4.4 iso" {
insmod ext2
set isofile="/administrator/packages/iso/android/android-x86-4.4-RC2.iso"
loopback loop (hd0,6)$isofile
linux (loop)/kernel  boot=/ iso-scan/filename=$isofile noeject
initrd (loop)/initrd.img
}

menuentry "Android 4.3" {
set root=(hd0,8)
linux /android-4.3-test/kernel quiet root=/dev/ram0 androidboot.hardware=android_x86 SRC=/android-4.3-test DATA= video=-16
initrd /android-4.3-test/initrd.img
}
