#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Ubuntu 13.04 ISO" {
	insmod ntfs
	set isofile="/packages/iso/ubuntu-13.04-desktop-amd64.iso"
	#isofile is the path of iso file in the corresponding partition 
	loopback loop (hd0,6)$isofile
	linux (loop)/casper/vmlinuz.efi boot=casper iso-scan/filename=$isofile noprompt noeject
	initrd (loop)/casper/initrd.lz
}

